data_path: './examples/sample_data/resource_usage_example_TRAIN.csv'
model_path: './models/lstm_resource_usage_example.keras'
preprocessing_parameters:
  dataset_splitting_parameters:
    training_portion: 0.8
    validation_portion: 0.2
  initial_timedelta: '1min'
  target_timedelta: '5min'
  training_window_size: 50000
  value_scaling_bounds:
    min: 0
    max: 100
forecasting_parameters:
  input_width: 6
  output_width: 6
model_compilation_parameters:
  loss_function: 'mse'
  max_epochs: 100
  optimizer: 'adam'
  input_layer_lstm_unit_count: 16
  early_stopping:
    patience: 10