data_path: str()
model_path: str()
variable_selection: include('variable_selection')
preprocessing_parameters: include('preprocessing_parameters')
model_training_parameters: include('model_training_parameters', required=False)
forecasting_parameters: include('forecasting_parameters')
---
variable_selection:
  endogenous_variables: list(str())
  exogenous_variables: list(str(), required=False)
---
preprocessing_parameters:
  dataset_timedelta: str()
  training_window_size: int(min=1)

model_training_parameters:
  use_auto_params: bool(required=False)
  max_p: int(min=0)
  max_q: int(min=0)

forecasting_parameters:
  forecast_horizon_size: int(min=1)