data_path: './examples/sample_data/univar_data/cpu_example_5min_TRAIN.csv'
model_path: './models/arima_resource_cpu_example_6_step.pkl'
target_variable: 'value'
preprocessing_parameters:
  dataset_timedelta: '5min'
  training_window_size: 50000
model_training_parameters:
  use_auto_arima: False
  default:
    max_p: 6
    max_d: 1
    max_q: 4
forecasting_parameters:
  forecast_horizon_size: 6  # next 30 minutes