data_path: './examples/sample_data/resource_usage_example_TRAIN.csv'
model_path: './models/arima_resource_usage_example.pkl'
preprocessing_parameters:
  initial_timedelta: '1min'
  target_timedelta: '5min'
  training_window_size: 50000
model_training_parameters:
  use_auto_arima: True
  default:
    max_p: 7
    max_d: 5
    max_q: 7
forecasting_parameters:
  forecast_horizon_size: 6