data_path: './examples/sample_data/multivar_data/multivar_example_5m_TRAIN.csv'
model_path: './models/multivar_lstm_example.keras'
variable_selection:
  input_variables:
    - "cpu_usage_percentage"
    - "mem_usage_percentage"
  output_variables:
    - "cpu_usage_percentage"
    - "mem_usage_percentage"
preprocessing_parameters:
  dataset_splitting_parameters:
    training_portion: 1.0
    validation_portion: 0.0
  training_window_size: 50000
  dataset_timedelta: "5min"
forecasting_parameters:
  input_width: 12
  output_width: 12
model_compilation_parameters:
  loss_function: 'mse'
  max_epochs: 100
  optimizer: 'adam'
  input_layer_lstm_unit_count: 128
  early_stopping:
    patience: 10